-- Minor hardening found via get_advisors while working on the index
-- audit: _fn_restore_pk_columns (added in Phase 17) was missing
-- `set search_path`, unlike every other function in this schema.
create or replace function public._fn_restore_pk_columns(p_table_name text)
returns text[]
language sql
immutable
set search_path to 'public'
as $function$
  select case p_table_name
    when 'provinces' then array['code']
    when 'query_sources' then array['code']
    when 'units' then array['code']
    when 'role_permissions' then array['permission_key']
    when 'unit_conversions' then array['from_unit','to_unit']
    when 'user_roles' then array['user_id','role_id']
    when 'roles' then array['id']
    when 'company' then array['id']
    when 'warehouses' then array['id']
    when 'chart_of_accounts' then array['id']
    when 'expense_heads' then array['id']
    when 'bank_accounts' then array['id']
    when 'petty_cash_funds' then array['id']
    when 'vehicles' then array['id']
    when 'items' then array['id']
    when 'item_alt_units' then array['id']
    when 'product_templates' then array['id']
    when 'product_template_lines' then array['id']
    when 'parties' then array['id']
    when 'party_contacts' then array['id']
    when 'queries' then array['id']
    when 'quotations' then array['id']
    when 'quotation_revisions' then array['id']
    when 'quotation_lines' then array['id']
    when 'sales_orders' then array['id']
    when 'sales_order_lines' then array['id']
    when 'sales_order_revisions' then array['id']
    when 'purchase_orders' then array['id']
    when 'purchase_order_lines' then array['id']
    when 'grns' then array['id']
    when 'grn_lines' then array['id']
    when 'jobs' then array['id']
    when 'job_material_requirements' then array['id']
    when 'job_cost_ledger' then array['id']
    when 'stock_reservations' then array['id']
    when 'stock_ledger' then array['id']
    when 'stock_adjustments' then array['id']
    when 'stock_transfers' then array['id']
    when 'stock_transfer_lines' then array['id']
    when 'delivery_challans' then array['id']
    when 'delivery_challan_lines' then array['id']
    when 'invoices' then array['id']
    when 'invoice_lines' then array['id']
    when 'supplier_bills' then array['id']
    when 'supplier_bill_lines' then array['id']
    when 'sales_returns' then array['id']
    when 'sales_return_lines' then array['id']
    when 'purchase_returns' then array['id']
    when 'purchase_return_lines' then array['id']
    when 'payments' then array['id']
    when 'payment_allocations' then array['id']
    when 'contra_transfers' then array['id']
    when 'expenses' then array['id']
    when 'journal_entries' then array['id']
    when 'journal_lines' then array['id']
    when 'numbering_sequences' then array['id']
    when 'daily_snapshots' then array['id']
    when 'tasks' then array['id']
    when 'activity_timeline' then array['id']
    when 'attachments' then array['id']
    when 'audit_log' then array['id']
    when 'import_batches' then array['id']
    when 'login_sessions' then array['id']
    when 'profiles' then array['id']
    else null
  end;
$function$;
