-- ============================================================
-- Phase 15 part B: Daily Snapshot (prompt's Daily Summary ask, §46) — a
-- point-in-time capture of the company's key numbers for a given day,
-- stored so the Owner can look back at "what was the position on day X"
-- without re-deriving it from journal_lines every time. Generated
-- automatically once a day via pg_cron (00:10, for the day that just
-- closed, so every transaction for that day is guaranteed already
-- posted); also callable manually (Owner) to backfill or regenerate.
-- ============================================================

create table public.daily_snapshots (
  id uuid primary key default gen_random_uuid(),
  snapshot_date date not null unique,
  cash_in_hand numeric(14,2) not null default 0,
  bank_balance numeric(14,2) not null default 0,
  petty_cash_balance numeric(14,2) not null default 0,
  stock_value numeric(14,2) not null default 0,
  total_ar_outstanding numeric(14,2) not null default 0,
  total_ap_outstanding numeric(14,2) not null default 0,
  sales_today numeric(14,2) not null default 0,
  collections_today numeric(14,2) not null default 0,
  payments_today numeric(14,2) not null default 0,
  expenses_today numeric(14,2) not null default 0,
  generated_at timestamptz not null default now(),
  generated_by uuid references auth.users(id)
);

comment on table public.daily_snapshots is 'One row per calendar day — a point-in-time capture of cash/bank/petty-cash/stock/AR/AP plus that day''s sales/collections/payments/expenses, generated by pg_cron nightly (or manually by Owner). Never recomputed retroactively when regenerated for the same date — fn_generate_daily_snapshot upserts, so a manual re-run always reflects the latest ledger state for that date.';

create index idx_daily_snapshots_date on public.daily_snapshots(snapshot_date desc);

alter table public.daily_snapshots enable row level security;
create policy p_select on public.daily_snapshots for select using (true);

create or replace function public.fn_generate_daily_snapshot(p_date date default current_date)
 returns uuid
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_cash numeric;
  v_bank numeric;
  v_petty numeric;
  v_stock numeric;
  v_ar numeric;
  v_ap numeric;
  v_sales numeric;
  v_collections numeric;
  v_payments numeric;
  v_expenses numeric;
  v_id uuid;
begin
  if not (public.is_owner() or public.has_role('accounts')) then
    raise exception 'Sirf Owner ya Accounts Daily Snapshot generate kar sakte hain.';
  end if;

  select coalesce(balance, 0) into v_cash from public.cash_in_hand_balance;
  select coalesce(sum(balance), 0) into v_bank from public.bank_account_balances;
  select coalesce(sum(balance), 0) into v_petty from public.petty_cash_fund_balances;
  select coalesce(sum(stock_value), 0) into v_stock from public.current_stock;
  select coalesce(sum(total_outstanding), 0) into v_ar from public.party_ar_summary;
  select coalesce(sum(total_outstanding), 0) into v_ap from public.party_ap_summary;

  select coalesce(sum(grand_total), 0) into v_sales
    from public.invoices where invoice_date = p_date and status = 'Posted';
  select coalesce(sum(amount), 0) into v_collections
    from public.payments where payment_date = p_date and status = 'Posted' and direction = 'receipt';
  select coalesce(sum(amount), 0) into v_payments
    from public.payments where payment_date = p_date and status = 'Posted' and direction = 'payment';
  select coalesce(sum(amount), 0) into v_expenses
    from public.expenses where expense_date = p_date and status = 'Posted';

  insert into public.daily_snapshots
    (snapshot_date, cash_in_hand, bank_balance, petty_cash_balance, stock_value, total_ar_outstanding, total_ap_outstanding,
     sales_today, collections_today, payments_today, expenses_today, generated_by)
  values
    (p_date, v_cash, v_bank, v_petty, v_stock, v_ar, v_ap, v_sales, v_collections, v_payments, v_expenses, auth.uid())
  on conflict (snapshot_date) do update set
    cash_in_hand = excluded.cash_in_hand,
    bank_balance = excluded.bank_balance,
    petty_cash_balance = excluded.petty_cash_balance,
    stock_value = excluded.stock_value,
    total_ar_outstanding = excluded.total_ar_outstanding,
    total_ap_outstanding = excluded.total_ap_outstanding,
    sales_today = excluded.sales_today,
    collections_today = excluded.collections_today,
    payments_today = excluded.payments_today,
    expenses_today = excluded.expenses_today,
    generated_at = now(),
    generated_by = excluded.generated_by
  returning id into v_id;

  return v_id;
end;
$function$;

-- System-generated snapshot (pg_cron has no signed-in user, so auth.uid()
-- is null and the role check above would reject it) — a separate
-- SECURITY DEFINER wrapper with no privilege check, callable only by the
-- cron job itself (never exposed to PostgREST/anon/authenticated).
create or replace function public._fn_cron_generate_daily_snapshot()
 returns void
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
begin
  perform public.fn_generate_daily_snapshot(current_date - 1);
end;
$function$;

revoke all on function public._fn_cron_generate_daily_snapshot() from public, anon, authenticated;

create extension if not exists pg_cron with schema extensions;

select cron.schedule('daily-snapshot', '10 0 * * *', $$select public._fn_cron_generate_daily_snapshot()$$);
